### ISSUE TITLE
Android projects don't seem to handle natives correctly?

### ISSUE THREAD

**Issue by tommyettinger** [czyzby/gdx-setup#20]
I can generate a project just fine with gdx-setup (I downloaded the latest nightly linked from the main page), and can even run certain tasks for the project (like `desktop:run`) from the command line, but I can't import the project into IntelliJ IDEA and I can't run basic tasks like `gradlew tasks`. There's an error in IDEA about missing the armeabi native jar that should be part of gdx-platform, and it offers to show the log, but IDEA apparently can't load that... since it freezes if I try to view the log. I initially got an error running `gradlew tasks` that showed a stacktrace that led to me updating to the Android 23.0.3 tools. Since then, no stacktrace but no improvement in the error either. I'm having a hard time tracking down the actual source of this bug, and it's very possible it's a local configuration issue, but it hasn't happened at all with the normal libGDX setup-ui. Here's the relevant info, with a few hundred lines of internal gradle stacktrace removed:

```
$ gradlew tasks --stacktrace
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\android\build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':android'.
> Could not resolve all dependencies for configuration ':android:natives'.
   > Could not find gdx-platform-natives-armeabi.jar (com.badlogicgames.gdx:gdx-platform:1.9.2).
     Searched in the following locations:
         file:/C:/Users/noto/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.2/gdx-platform-1.9.2-natives-armeabi.jar

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':android'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:157)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
...
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':android:natives'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:70)
...
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 71 more
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find gdx-platform-natives-armeabi.jar (com.badlogicgames.gdx:gdx-platform:1.9.2).
Searched in the following locations:
    file:/C:/Users/noto/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.2/gdx-platform-1.9.2-natives-armeabi.jar
        at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:38)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.resolveArtifact(ExternalResourceResolver.java:247)
...
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolvedConfiguration.getFiles(ErrorHandlingConfigurationResolver.java:197)
        ... 90 more


BUILD FAILED

Total time: 1.515 secs
```

And here's the results of it with `--info` on instead of `--stacktrace`:

```
$ gradlew tasks --info
Connected to daemon DaemonInfo{pid=6008, address=[34a8d807-0143-4399-aa3d-6e066f967371 port:49258, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=true, context=DefaultDaemonContext[uid=b0dbe4a4-a285-4009-8f81-f9d16bb1548a,javaHome=C:\Program Files\Zulu\zulu-8,daemonRegistryDir=C:\Users\noto\.gradle\daemon,pid=6008,idleTimeout=10800000,daemonOpts=-Xms128m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=227e6adf-23df-462f-a87d-e4f8ee2ea4f8.1, currentDir=C:\Users\noto\Documents\GitHub\GdxSetupTestSquid}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@4e928fbf from daemon DaemonInfo{pid=6008, address=[34a8d807-0143-4399-aa3d-6e066f967371 port:49258, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=true, context=DefaultDaemonContext[uid=b0dbe4a4-a285-4009-8f81-f9d16bb1548a,javaHome=C:\Program Files\Zulu\zulu-8,daemonRegistryDir=C:\Users\noto\.gradle\daemon,pid=6008,idleTimeout=10800000,daemonOpts=-Xms128m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 6008). The daemon log file: C:\Users\noto\.gradle\daemon\2.13\daemon-6008.out.log
Starting 6th build in daemon [uptime: 14 mins 40.348 secs, performance: 93%, memory: 56% of 477.6 MB]
Executing build with daemon context: DefaultDaemonContext[uid=b0dbe4a4-a285-4009-8f81-f9d16bb1548a,javaHome=C:\Program Files\Zulu\zulu-8,daemonRegistryDir=C:\Users\noto\.gradle\daemon,pid=6008,idleTimeout=10800000,daemonOpts=-Xms128m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
Starting Build
Settings evaluated using settings file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\build.gradle'.
Included projects: [root project 'GdxSetupTestSquid', project ':android', project ':core', project ':desktop', project ':gwt']
Configuration on demand is an incubating feature.
Evaluating root project 'GdxSetupTestSquid' using build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\build.gradle'.
Evaluating project ':android' using build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\android\build.gradle'.
Creating configuration compile
Creating configuration apk
Creating configuration provided
Creating configuration wearApp
Creating configuration androidTestCompile
Creating configuration androidTestApk
Creating configuration androidTestProvided
Creating configuration androidTestWearApp
Creating configuration testCompile
Creating configuration testApk
Creating configuration testProvided
Creating configuration testWearApp
Creating configuration debugCompile
Creating configuration debugApk
Creating configuration debugProvided
Creating configuration debugWearApp
Creating configuration testDebugCompile
Creating configuration testDebugApk
Creating configuration testDebugProvided
Creating configuration testDebugWearApp
Creating configuration releaseCompile
Creating configuration releaseApk
Creating configuration releaseProvided
Creating configuration releaseWearApp
Creating configuration testReleaseCompile
Creating configuration testReleaseApk
Creating configuration testReleaseProvided
Creating configuration testReleaseWearApp
Creating configuration instrumentTestCompile
Creating configuration instrumentTestApk
Creating configuration instrumentTestProvided
Creating configuration instrumentTestWearApp
Evaluating project ':core' using build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\core\build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\android\build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':android'.
> Could not resolve all dependencies for configuration ':android:natives'.
   > Could not find gdx-platform-natives-armeabi.jar (com.badlogicgames.gdx:gdx-platform:1.9.2).
     Searched in the following locations:
         file:/C:/Users/noto/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.2/gdx-platform-1.9.2-natives-armeabi.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 1.603 secs
Stopped 0 compiler daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file 'C:\Users\noto\Documents\GitHub\GdxSetupTestSquid\android\build.gradle' line: 46
A problem occurred evaluating project ':android'.] from daemon DaemonInfo{pid=6008, address=[34a8d807-0143-4399-aa3d-6e066f967371 port:49258, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=true, context=DefaultDaemonContext[uid=b0dbe4a4-a285-4009-8f81-f9d16bb1548a,javaHome=C:\Program Files\Zulu\zulu-8,daemonRegistryDir=C:\Users\noto\.gradle\daemon,pid=6008,idleTimeout=10800000,daemonOpts=-Xms128m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
```

The mentioned jar, gdx-platform-1.9.2-natives-armeabi.jar, does not exist in the location it's searching, though one other native jars is  there: gdx-platform-1.9.2-natives-desktop.jar. I've produced APKs with LibGDX 1.9.2 on earlier projects, so I don't think the armeabi jar is needed in the searched location to work with Android stuff.

Both this error and the difficulty getting more information about it are very strange, and I think the different handling of the native platform jars in this project compared to setup-ui may be a possible culprit. Are there any recent changes in native/platform-jar behavior, or possibly differences in local configuration between the .m2 folders used by developers and my .m2 folder with lots of Maven libraries already installed?

**Comment by czyzby** [comment]
That's strange, the Android project seems to work locally on Linux (Mint) and @kotcrab 's Windows. Chances are you're using the wrong versions somewhere. Are you sure that the correct Android target API and build tools are chosen? Try clicking the up and down arrow buttons near the Android SDK to automatically. choose the appropriate versions.

**Comment by czyzby** [comment]
This is one of the default templates running in an Android emulator via Android Studio - the project was imported as Gradle project, and no changes were required whatsoever.

![android](https://cloud.githubusercontent.com/assets/11707612/15109948/582379c0-15de-11e6-9987-bd305e72f0b1.png)

**Comment by kotcrab** [comment]
I can import Android project just fine into IDEA and run it on real device. IDEA gives proper errors when it can't find build tools: "failed to find Build Tools revision xx.x.x". I don't have `gdx-platform-1.9.2-natives-armeabi.jar` in that location either.

**Comment by czyzby** [comment]
I corrected the Android native dependencies, although I'm afraid the jar you mentioned was already included. @tommyettinger - could you download the snapshot and try now?

**Comment by czyzby** [comment]
@tommyettinger - does the problem still occur when using latest version with LibGDX 1.9.3?

**Comment by tommyettinger** [comment]
Seems completely fixed here. I don't know what caused the problems the first time, but I have no problems with the latest download. Thanks @czyzby ! I'll close this if you don't mind.

**Comment by czyzby** [comment]
Android natives are downloaded and copied using Gradle, so my guess is that there was something wrong with Gradle itself - maybe you interrupted an Android-related task or used old Gradle version? Anyway, I don't mind closing this issue, as I was unable to reproduce this problem in the first place - I'm glad it works for you now.

**Comment by tommyettinger** [comment]
That seems likely, that something was interrupted. (Possibly antivirus scan didn't like something downloading? Possibly my hard drive is in a sad state?)
