### ISSUE TITLE
Gradle wrapper

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#5]
- [x] Optional advanced property: include Gradle wrapper.
- [x] Optional advanced property: name of Gradle tasks to run after generation.

Gradle wrapper was excluded from the initial `gdx-setup` on purpose - it makes the jar a lot bigger, forces a specific Gradle version and thanks to *not* running the Gradle tasks, the generation takes a fraction of second instead of up to a few minutes.

However, Gradle wrapper might be useful to beginners and people that - for any reason - do not want to install Gradle globally. It should be possible to ***optionally*** include Gradle wrapper and run any Gradle tasks right after the initial generation.

**Comment by czyzby** [comment]
@kotcrab Can you check if running post-generation Gradle tasks works on Windows? You can find this property in `Advanced` tab.

**Comment by kotcrab** [comment]
With wrapper:
```
java.io.IOException: Cannot run program "gradlew.bat" (in directory "C:\Users\Kotcrab\Desktop\artest"): CreateProcess error=2, Nie można odnaleźć określonego pliku
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.czyzby.setup.data.project.Project.includeGradleWrapper(project.kt:151)
	at com.github.czyzby.setup.views.dialogs.GenerationPrompt$doBeforeShow$1.run(generationPrompt.kt:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, Nie można odnaleźć określonego pliku
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
```
Without wrapper:
```
java.io.IOException: Cannot run program "gradle" (in directory "C:\Users\Kotcrab\Desktop\artest"): CreateProcess error=2, Nie można odnaleźć określonego pliku
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.czyzby.setup.data.project.Project.includeGradleWrapper(project.kt:151)
	at com.github.czyzby.setup.views.dialogs.GenerationPrompt$doBeforeShow$1.run(generationPrompt.kt:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, Nie można odnaleźć określonego pliku
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
```

`gradlew.bat` is present in this directory and `gradle` command is available globally from cmd

**Comment by czyzby** [comment]
Could you modify `project.kt` at 168? Try this: `basic.destination.file().absolutePath + "\\gradlew.bat"` and use the wrapper.

**Comment by kotcrab** [comment]
`basic.destination.file().absolutePath + File.separator + "gradlew.bat"` works when using wrapper.

**Comment by czyzby** [comment]
Pull and try now.

**Comment by kotcrab** [comment]
It works now, tested with and without wrapper. By the way I think it's worth explicitly saying that putting `gradlew` inside task field is not needed, it's a bit unclear now.
