### ISSUE TITLE
There is no OpenGL context current in the current thread.

### ISSUE THREAD

**Issue by hacker1024** [czyzby/gdx-setup#54]
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

```
Exception in thread "main" java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:347)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:299)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:448)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
        at com.github.czyzby.setup.MainKt.main(main.kt:24)
```

**Comment by czyzby** [comment]
This seems like a LibGDX issue. I believe [this might be the fix](https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/main.kt#L32-L38) for your problem. Try setting `XstartOnFirstThread` flag when running the application. Are you using a Mac?

**Comment by hacker1024** [comment]
Thanks for replying so quickly!
XstartOnFirstThread doesn't help.
I'm using Arch Linux on a desktop PC

**Comment by czyzby** [comment]
It might be an issue with your OpenGL settings. Can you check if you can run empty LibGDX applications (using both LWJGL 2 and 3) generated with the official gdx-setup?

**Comment by hacker1024** [comment]
I can run a LibGDX app with the default settings, I don't know what LWJGL version is used or how to change it.
I've been able to run any other app/game that uses LWJGL on this computer.

**Comment by czyzby** [comment]
`gdx-setup` uses LWJGL 3, [this blog post](www.badlogicgames.com/wordpress/?p=3870) describes how to migrate. Can you also check if you can run LWJGL 3 apps?

**Comment by yulens** [comment]
Had same issue on linux with openjdk 1.8.0_151. Solved by updating libGDX version in `gradle.properties` to 1.9.8.

**Comment by czyzby** [comment]
Thanks @yulens, I'll update `gdx-setup` this weekend.

**Comment by czyzby** [comment]
LibGDX version will be updated in #61.
